language: objective-c

osx_image: xcode7.3
env:
  - TEST_DIR=Example/TSKitiOSTestApp

before_install:
  - cd $TEST_DIR
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - gem install cocoapods xcpretty --no-ri --no-rdoc
  - pod repo update --silent

install: pod install

script:
- |
  set -o pipefail
  xcodebuild -workspace TSKitiOSTestApp.xcworkspace \
             -scheme TSKitiOSTestApp \
             -sdk iphonesimulator \
             -destination 'platform=iOS Simulator,name=iPhone 6' \
             build test | xcpretty

xcode_workspace: TSKitiOSTestApp.xcworkspace
xcode_scheme: TSKitiOSTestApp

